--liquibase formatted sql
--changeset two:0.1.2 endDelimiter:;
ALTER TABLE TMP_1.APPLICATION_PARAMETER 
ADD STATUS VARCHAR(10) NULL;
--rollback ALTER TABLE TMP_1.APPLICATION_PARAMETER DROP COLUMN STATUS;
