--liquibase formatted sql
--changeset one:0.1.1 endDelimiter:;
INSERT INTO TMP_1.APPLICATION_PARAMETER
(CATEGORY, NAME, VALUE, VERSION)
VALUES('WEB', 'test2', 'val', 1);
--rollback DELETE FROM TMP_1.APPLICATION_PARAMETER WHERE CATEGORY='WEB' AND NAME='test2';

--liquibase formatted sql
--changeset one:0.1.2 endDelimiter:;
INSERT INTO TMP_1.APPLICATION_PARAMETER
(CATEGORY, NAME, VALUE, VERSION)
VALUES('WEB', 'test3', 'val', 1);
--rollback DELETE FROM TMP_1.APPLICATION_PARAMETER WHERE CATEGORY='WEB' AND NAME='test3';
