INSERT ALL
   INTO TMP_1.APPLICATION_PARAMETER (CATEGORY, NAME, VALUE, VERSION) VALUES ('WEB', 'test4', 'val', 1)
   INTO TMP_1.APPLICATION_PARAMETER (CATEGORY, NAME, VALUE, VERSION) VALUES ('WEB', 'test5', 'val', 1)
   select * from dual